# run: conda env create --file base.yml
name: base
channels:
  - defaults
  # - conda-forge
dependencies:
  - git
  - conda-forge::gh
  # - conda-libmamba-solver
  - ipywidgets
  - jupyterlab
  - nb_conda_kernels
  - pip
  - python==3.10
  - conda-forge::vim
#  - mamba
  - pip:
      - black
      - nbdime
      - jupyterlab-code-formatter
      - jupyterlab-vim
      - jupyterlab-lsp[all]
      - jedi-language-server
